name: Build
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build -- --linux
      - uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build -- --mac
      - uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: dist/